name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - mdtraj
  - numba
  - netcdf4

#  - tqdm
#  - matplotlib
#  - ipympl
#  - mpld3
#  - numba
#  - pytest
#  - pytest-cov
#  - tox
#  - nbdime
#  - nbstripout
#  - sphinx
#  - recommonmark
#  - mdtraj
#  - prody
#  - raft-dask
#  - cuda-version=12.0
#  - cuda-cudart
#  - cupy
#  - pylibraft

  - pip:
     - -e .
     - numba-kdtree
     - git+https://github.com/rglez/rgpack.git@0.0.3
