name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipython
  - mdtraj
  - numba
  - netcdf4
  - tqdm
  - numba
  - mdtraj
  - pytest
  - pytest-cov
  - mdanalysis
  - rdkit

  - pip:
     - -e .
     - numpy-indexed
     - git+https://github.com/rglez/rgpack.git@0.0.3
     - numba_kdtree
