name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  # not necessary for the package. Remove when published.
  - prolif
  - matplotlib
  - ipython
  - pytest
  - pytest-cov

  - python>=3.6
  - pip
  - numpy
  - pandas
  - tqdm

  - numba
  - mdanalysis
  - rdkit
  - bitarray == 3.0.0

  - pip:
      - -e .
      - numba_kdtree
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
