name: intermap
channels:
  - defaults
  - conda-forge
dependencies:

  # Python
  - python
  - ipython

  # Testing
  - pytest
  - pytest-cov
  - matplotlib

  # Molecular
  - mdtraj
  - mdanalysis
  - rdkit

  # Numerical
  - numpy
  - bitarray ~= 3.0.0
  - numba ~= 0.61.0

  # From pip
  - pip
  - pip:
      - -e .
      - memory_profiler # Development only
      - numpy_indexed
      - numba_kdtree == 0.5.0
      - pytest-randomly
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
