name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  # not necessary for the package. Remove when published.
  - pytest
  - prolif
  - pytest-cov
  - matplotlib
  - tqdm

  - pandas
  - ipython
  - python
  - numpy

  - bitarray == 3.0.0
  - numba == 0.61.0
  - mdtraj
  - mdanalysis
  - rdkit

  - pip
  - pip:
      - -e .
      - numpy_indexed
      - numba_kdtree
      - pytest-randomly
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
