name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - mdanalysis
  - mdtraj
  - rdkit
  - numpy
  - pandas
  - bitarray ~= 3.0.0
  - numba ~= 0.61.0
  - pip
  - pip:
      - -e .
      - uvicorn
      - shiny
      - plotly
      - screeninfo
      - numpy_indexed
      - numba_kdtree == 0.5.0
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
