name: intermap
channels:
  - defaults
  - conda-forge
dependencies:
  # not necessary for the package. Remove when published.
  - pytest
  - prolif
  - pytest-cov
  - matplotlib
  - tqdm

  - pandas
  - ipython
  - python>=3.6
  - numpy==1.23.1

  - numba
  - mdtraj == 1.9.4
  - mdanalysis
  - rdkit
  - bitarray == 3.0.0

  - pip
  - pip:
      - -e .
      - numpy_indexed
      - numba_kdtree
      - pytest-randomly
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
