name: intermap
channels:
  - defaults
  - conda-forge
  - rapidsai
  - nvidia
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
#  - tqdm
  - ipython
#  - matplotlib
#  - ipympl
#  - mpld3
#  - numba
#  - pytest
#  - pytest-cov
#  - tox
#  - nbdime
#  - nbstripout
#  - sphinx
#  - recommonmark
#  - mdtraj
#  - prody
  - raft-dask
  - cuda-version=12.0
  - cuda-cudart
  - cupy
  - pylibraft

  - pip:
     - -e .
